# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_inj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
