CC = gcc -g
CFLAGS=-std=gnu11 -Wall -Werror

BINS = task1 task2 task3 task4 task6

all: $(BINS)

task1: task1.c common.h

task2: task2.c procword.h common.h

task3: task3.c procword.h common.h

task4: task4.c common.h

task6: task6.c common.h

clean:
	rm -vf $(BINS)

