:- module(tests, [tests/5]).

:- op(200, fx, ~).
:- op(500, xfy, v).


%% The most basic cases

tests(one_literal, validity, [p], 1000, solution([(p, t)])).
tests(negated_literal, validity, [~p], 1000, solution([(p, f)])).

tests(two_same, validity, [p, p], 1000, solution([(p, t)])).
tests(two_same_c, validity, [p, p], 1000, count(1)).

tests(two_negations, validity, [~p, ~p], 1000, solution([(p, f)])).
tests(two_negations_c, validity, [~p, ~p], 1000, count(1)).

%% Basic with alternatives

tests(two_true, validity, [p v q], 1000, solution([(p, t)])).
tests(two_true_c, validity, [p v q], 1000, count(2)).

tests(excluded_middle, validity, [~p v p], 1000, solution([(p, t)])).

tests(doubled, validity, [p v q, ~p v ~q], 1000, solution( [(p, t), (q, f)])).
tests(doubled_c, validity, [p v q, ~p v ~q], 1000, count(2)).

%% Three-variables

tests(basic1, validity, [p v ~q v r, r], 1000, solution([(p, t), (r, t)])).
tests(basic1_c, validity, [p v ~q v r, r], 1000, count(3)).

tests(basic2, validity, [p v q v r, ~p v ~q v ~r], 1000,
              solution( [(p, t),  (q, f)])).
tests(basic2_c, validity, [p v q v r, ~p v ~q v ~r], 1000, count(6)).

tests(basic3, validity, [p v q v r, ~r v ~q v ~p, ~q v r, ~r], 3000,
              solution( [(p, t), (r, f), (q, f)])).

%% Unsolvable tests

tests(unsolvable_basic, validity, [p, ~p], 1500, count(0)).
tests(unsolvable_alternative, validity, [p v q, ~p, ~q], 1500, count(0)).
tests(unsolvable_complex, validity, [p v q v ~r, ~p, ~q v p, r], 1500, count(0)).

%% Multiple variables

tests(fourVars, validity, [p v q v r v w, ~p, ~r, q], 3000,
                solution( [(w, t), (p, f), (r, f), (q, t)])).
tests(fourVars_c, validity, [p v q v r v w, ~p, ~r, q], 3000, count(2)).

tests(fiveVars, validity, [p v q v r v w, ~p, ~r, q, p v ~q v o, w v r], 4000,
                solution( [(p, f),  (r, f),  (q, t),  (o, t),  (w, t)])).

%% Chaining

tests(chaining, validity,
      [p, ~p v q, ~q v r, ~r v w, ~w v o, ~o v k], 5000,
      solution([(p, t),  (q, t),  (r, t),  (w, t),  (o, t),  (k, t)])).
tests(chaining_c, validity,
      [p, ~p v q, ~q v r, ~r v w, ~w v o, ~o v k], 5000, count(1)).

%% Multiple solutions

% [3 vars, 3 vars] 3*3 = 9
tests(many_solutions, validity,
      [p v q v r, w v u v o], 2000, count(9)).

% [5 vars, 5 vars] 5*5 = 25
tests(square_solutions, validity,
      [p v q v r v n v m, w v u v o v k v s], 2500, count(25)).

% [3 vars, 3 vars, 3 vars] 3*3*3 = 27
tests(cubic_solutions, validity,
      [p v q v r, n v m v w, u v o v k], 3000, count(27)).

% [3 vars, 3 vars, 3 vars, 3 vars, 3 vars] 3^5 = 243
tests(even_more_solutions, validity,
      [p v q v r, n v m v w, u v o v k, a v b v c, d v e v f], 8000, count(243)).
%% tests(generator, performance, [~j v k v ~c v g, ~i v o v ~b v f, ~h v n v ~f v e, ~g v m v ~e v i, ~f v l v ~d v h], 5000, count(11520)).
tests(generator, performance, [~j v k v ~c v g, ~i v o v ~b v f, ~h v n v ~f v e, ~g v m v ~e v i, ~f v l v ~d v h], 5000, count(11520)).
tests(big_tests0, performance, [~r v b, ~r v k v p v g, ~r v q v ~l v h v m, ~q v ~m v ~o v i v b v ~n v b v n, ~q v ~h v ~p v m v b v j v j v o, ~p v ~e v ~i v f v n v ~c v d v r, ~p v f v ~m v l v i, ~o v ~l, ~o v c v ~m v ~e v q v ~b v k v h, ~n v ~n v ~g v q v o, ~n v ~d v ~c v ~m v c v ~p v f v ~b v ~e v i, ~n v ~b v ~e v ~j, ~n v h v d, ~m v ~e v ~k, ~m v p v ~h v b v ~l v ~n v d v f v m, ~l v ~o, ~l v ~n v q v ~f, ~l v b, ~k v ~c v k v ~m v ~p, ~k v d v e, ~k v d v m, ~j v ~l v f v e v b, ~j v i, ~j v k v d v j v ~h v p v l, ~j v p v ~n v ~k, ~j v q v n, ~i v ~r v ~h v ~r v ~j, ~i v f v ~b v ~r v f v j v ~b v k v q, ~i v i v b v d v ~m v ~r v ~m v q v ~g, ~i v q v ~c v i v d v ~p v ~e v ~g, ~h v ~p v r v r v c v f, ~g v ~g v ~j v ~c v b v f v ~f, ~g v c v ~q, ~f v ~k v p v ~c v d v m v e v f, ~f v ~c v ~e v f v ~f v f v d v d v ~f, ~f v m v ~n, ~e v ~o v f v ~h v ~o v ~f v l, ~e v b v ~c v ~j v ~o v o, ~d v ~f v g v ~l v ~d v ~i, ~d v i v ~i v r v i v e v e v f v ~e, ~c v ~i v ~c v r v ~b v m, ~c v ~f v f v ~f v ~g v ~n v l v b v l v ~q, ~c v d, ~c v f v ~m v q, ~c v i v o, ~c v j v ~p, ~c v l v ~l v g v ~e v ~o v h, ~b v n v c v g v f, b v ~i v b, c v ~g v ~d v o v ~g v ~j v ~h, c v p v q, d v ~m v ~g v ~o v ~o v ~e v g v ~p v ~q v j, d v ~j v j v ~r v c v f v ~c v ~j, d v ~b v ~e v ~g v ~r v f, e v ~p v ~e v e v o v g v m v ~j v h, e v ~l v ~i v ~l, e v ~i v c v h, e v ~f v ~h v m v g v ~e v j v b v ~k, e v e v ~e v h v ~d, e v n v ~j v j v ~i v j, f v ~p, f v ~m v ~o v g v ~k v g v ~g v ~g v r v ~h, f v ~f v ~e v m v ~b v ~r v ~m v g v ~l v ~l, f v ~e v o v f v f v f v ~q v d v e, g v ~j v d v b v ~d v ~f, h v ~l v ~h v k v ~i v l v p, h v d, h v q, i v ~o v ~h v b v ~l, i v ~i v b v g v g v ~n v h, i v ~h v c, i v p v ~q, j v c v ~q v ~l v n v j, j v n v i v ~o, k v e v ~b v e v ~r v ~r v k v ~q v ~e, l v ~k v f v ~f v ~f v c, l v ~b v g, l v m v ~p v k, m v b v i, m v e, m v q v p v ~c v c v p v ~q v f v ~l, n v ~d, n v ~d v c v ~c, n v ~b v ~d v ~k v ~p v ~q v n v ~r v ~p, n v d v g v c v ~n v k v n, o v ~o v ~r v i v g v d v ~c v ~j v d v ~n, o v ~j v ~c v l v j v ~k v ~l, o v ~c v m v g, o v d v ~d v ~j v c v ~f v ~k v ~q, o v h v j v r v ~i v f v f v n v ~c v b, p v ~f v ~i v ~i v d v m v ~r, p v g v g v ~m v q v ~f, p v i v ~q v i v ~q v i v ~p v p, p v q, q v ~f v ~c v i, q v n v c v n v j v ~n v q v e, q v q v g v l v ~i v k v i v ~l v m v m, r v ~d v m v ~b v ~o v g v ~c v ~n v ~o, r v j, r v r], 500, count(67)).
tests(big_tests1, performance, [~r v e v e, ~r v g, ~q v f v ~o v o v m v ~o v p v ~e, ~q v l v e v b v e v ~p, ~p v ~n v i v h v ~f v h v r v ~e v ~f, ~o v ~c v r v ~e v j v p v ~m v ~g v ~g, ~o v o v ~n v ~o v ~l, ~n v ~n v ~o v l v k, ~n v ~k v m v p v ~p v ~m v ~k v p v ~n v r, ~n v ~h v p v r v ~m v ~o v ~n v i v g, ~n v ~g v ~e v n v ~b v ~f v m, ~n v ~e v ~p v k v ~l v ~c v f v ~f v g, ~n v ~d v ~i v ~f v b v o v ~m v g v ~q, ~n v b v ~q v ~m v ~e v ~e v ~c v g v ~q, ~n v c v m v i, ~n v o v ~h v l, ~m v ~g v q v f v c, ~l v ~r v b v k v o v ~m, ~l v ~q v k v f v ~f v ~d v q v r v ~n v ~l, ~l v ~n v l, ~l v i v ~m, ~l v l v k v ~k, ~l v r v i v r, ~l v r v l v i v ~p v ~c v ~m v p, ~k v ~l v l v ~l v k, ~k v k v ~o, ~k v r, ~j v ~g v q v f v ~k, ~i v ~l v g, ~i v d v ~o v n v ~m, ~i v e v ~k v ~m v ~n v g v h v o v p, ~h v ~p v d v ~p v m v ~d v q v ~l v ~l, ~g v ~p, ~g v b v r v ~p v c v q v ~e v ~m v q, ~g v c v ~q v i v ~h v k v ~g v ~d, ~g v j v n v ~b v r v ~b v ~h v r, ~f v ~q v r v e v e v o v b, ~f v ~j v k v p v f v q, ~f v ~h, ~f v ~g v ~h v ~f v ~b v h v ~g v ~l v i v f, ~f v f, ~f v o v ~k v ~k v ~c v ~n v ~d, ~e v l v r v k v ~b v ~e, ~d v ~p v ~c, ~d v ~f v ~k v o, ~c v ~l v h v p v ~o v l, ~c v g v p v ~q v ~m, ~b v ~p v ~h v c v ~r v p, ~b v ~l, ~b v c v ~h v ~f, ~b v j v ~p v e v m v ~k v e, ~b v o v ~f v ~b, ~b v p v ~f v c v p v ~q v ~g v ~m, b v ~i v ~m, b v ~e v g v ~l v e v ~c v b v ~j, b v h v k v ~m v f v l v ~d v ~h, c v ~k v e v ~r v l v p v g v ~r v ~l v p, d v ~g v e v m v ~p v ~k v m v ~l, d v ~f v ~f v ~n v l v q v ~p v ~g v e, d v j v b v ~p, d v m v ~j v p v ~e v ~k v n, d v n v l v ~d, d v r v ~q v o v ~p v g v ~f, d v r v ~e v ~o v m v g v ~o v f, e v ~o v p v l v g v e v i v ~c v k, e v c v i v g v j v ~f v ~l v h v r v ~m, e v j v ~i v ~c v f v ~j v ~j v ~n, f v ~r v ~i v e v ~e v ~f v k v c v ~d v g, f v ~n v e v o, f v ~j v q v ~q v ~i v ~n v ~f v ~m v h v ~c, f v g v g v ~c v r v ~e v g v ~g v ~q, f v i v b v b v ~m v c v j v ~i v r v ~q, g v ~m, g v ~e v g v k v ~q v e, i v f v n v c v h v ~f, j v ~e v k v r v ~d v ~d v l, j v c v b v ~c, j v r v b v q v m v ~j, l v ~l v n v ~c v ~q v ~e v d v ~l v ~o v ~p, l v f, m v ~r v m v h v ~r, m v ~n, n v ~m v ~j, n v ~g v m, n v ~g v n v ~b, n v ~e v e v ~f v ~f v k v ~i v ~h, n v d v r v r v e, n v g v ~k, o v c v k v ~g v j v ~c v o v ~p, o v g v f v f v ~c v r v ~f, o v j, o v p v h v ~r v h v k v d v ~k v c v o, o v r v q v ~d v g v m, p v ~m v ~l v o v b v r v c, p v i v ~h v ~r, q v ~j v ~l v ~f v i v ~p v n v m v ~j v c, q v p v h v ~d v ~l, r v ~h v h, r v g v ~o v i v b v ~r, r v i v e v e v ~e], 500, count(176)).
tests(big_tests2, performance, [~r v ~n v ~b v h v ~d v r v ~d v ~i v ~c, ~r v j v ~o v i v o v ~b v i v b, ~p v ~f v ~e v ~n v i v g, ~p v i, ~p v l v p v c v l v ~q v ~d v b v ~l, ~p v m v ~f, ~o v ~o v ~i v c, ~o v c v ~m v ~i, ~o v k v ~h, ~o v o v q v ~b v d v c, ~n v i v g v ~d, ~m v ~n v ~d v ~r v n v ~l v b v l, ~l v i v ~c, ~l v l, ~k v ~l v ~o v ~j v f v ~j v ~e, ~k v ~c v g v ~h v ~f v e v h v ~l v o v ~i, ~k v o v d v f v n v ~f, ~j v ~h v ~n v k v ~b v i v ~b v f v j v ~l, ~j v ~h v p v ~l v ~o v m v b v i v ~l, ~j v b v m v l v ~l v c, ~i v ~n v ~i v ~p v l v ~g v c v ~n, ~i v ~k v ~r v ~k, ~i v j v m v d v p v ~m, ~i v o v q v ~r v ~f v j v h, ~i v p v ~o v h v l v ~k v i v b v ~g v ~m, ~h v i v ~m, ~h v i v ~b v ~o v b v ~l v o v b v k, ~g v ~p v ~k v n v c v ~o, ~g v ~l, ~g v ~h v ~p v d v j v o v ~d, ~g v f v ~p, ~f v ~g v ~e v ~o, ~f v j v c v k v ~o, ~e v ~q v ~q v k v h, ~e v ~m v ~m, ~e v ~f v g v ~b v ~d v k, ~e v ~b v n v ~k, ~c v ~d v c v ~e v ~r v ~o v m v o v ~o, ~c v f v r, ~b v ~l, ~b v ~k v ~f v i v m v e v ~b v ~l v ~d v ~e, ~b v f v g v g v p v q v ~c v j, ~b v n v c v ~k v m v ~d v c v ~r v ~b v o, ~b v r v o v ~c v k v j v k, b v ~d v h v c v ~k v ~e v ~l v b v ~r v r, b v b v e v ~n v h v m v ~n v ~k, b v d v ~r v p, b v d v ~e v n v j, b v q v n v q v ~f v q v ~n v k, c v ~n v ~g v ~j, d v ~b v ~g v m v f v ~m v ~m v ~b v b v ~b, d v g v c, d v o, e v ~p v d v ~d v ~f v d v q, e v i v m v p v d v ~n v k, e v l v q, f v ~l v e v e v b v ~i v ~g v ~f v l v ~o, f v ~f v ~i v j v o v i v p v ~h, f v j v ~l v i, f v l v g v r v g v b v m v ~n v i v r, f v m, f v m v ~m v ~b v k, g v i v ~k v ~d v i v ~m v i v ~n v b v n, g v j v b v ~n v ~l v ~q v h v ~e v ~p, g v k v i v f v ~d v ~j v ~c v m, h v ~i v g v l v ~c v ~p v n v ~q v k, h v d v ~r v ~l v l v g v o, h v o v ~h v f, i v ~r v ~b v ~m v h v p v e v i v ~b v c, i v ~d v m v ~f v h v ~l, i v l v l v ~g v e v ~l, i v p v m v r v ~o v ~b, j v ~o v ~m v g v q v c v b, j v ~o v e v r v c v l v ~f v ~j v ~q, j v ~n v ~n v ~e v ~h v o v m v d, j v ~j v q, j v ~i v m v ~o v l v l v ~d, j v f v ~n, j v f v ~n v m v i v ~h v ~r v j, k v ~o v ~j v j v g v k v ~e v ~n, k v ~k v ~h, k v q, l v ~i v n v ~i v o v q v ~e v ~k, l v ~h v c v d v j v p v n v ~n v ~l v ~f, m v ~p v ~l v m v ~i v ~i v ~i v ~f, m v ~i v g, n v ~r v k v d v ~b v ~l v q v c v ~b v l, n v ~c v d v ~c v ~m v ~d, n v f v q v r v p v c v r, o v ~o v i v j v ~d v ~d, o v b, p v ~l, p v ~d v g v q v j, q v f, q v p v j, r v ~r v ~l v ~l v ~i v d v ~e v j v e v ~q, r v ~e, r v ~b v ~m v r v l v k v ~p v ~k v ~l, r v b v ~c v ~p v ~e v ~k v q v ~d v ~e v ~g, r v f v ~r], 500, count(1091)).
tests(big_tests3, performance, [~r v e v ~n v ~j v h v d, ~r v h v ~c, ~r v r v ~i v ~k v p v ~r v m v ~q v ~e, ~q v ~k v ~l v ~g v q v ~p v ~m v ~m, ~q v ~i v ~p v ~g v m, ~q v ~h v ~f v ~d v k v ~c v ~k v ~j v l v ~o, ~p v ~d v p v c v ~f, ~p v ~c, ~o v ~l v ~n v ~i, ~o v ~g v ~i, ~o v ~e v ~d v ~p v ~l v ~e, ~o v l v ~l v ~g v h v ~e v ~r, ~n v ~q v m v ~i v ~m v b, ~n v ~o v ~r v i v ~p v ~q v q v i v b v e, ~n v ~o v g v f v ~c v h, ~n v ~g v ~d v ~f v o, ~n v ~d, ~n v ~d v ~o v h v ~n v ~r v ~r, ~n v r v ~b v ~f v ~n v ~g v p v ~q v r, ~m v ~r v b v b v ~b v g v ~b v ~d, ~m v ~b v b v ~f v ~m v m, ~m v k v ~g v o v g v n v b, ~m v k v ~e v h v ~k v f v ~h v ~c, ~l v ~o, ~l v ~k v ~f v ~k v ~f, ~l v c v ~h v g v ~n v i v k v p v f, ~l v g v k, ~k v ~k v p v ~j v m v ~q v ~n v g v ~k, ~k v ~i v c v o v ~e v ~f v ~e, ~k v ~h v n v ~c, ~k v ~f v e v ~o v h v ~r v l v ~o, ~j v ~o v ~o v r v ~m, ~j v d v f v ~f v i v ~r v c v r v b, ~j v k v ~q v ~o v ~j v ~o v ~m, ~i v ~g v ~g v j, ~i v ~e v ~r v ~l, ~h v ~m v ~j v m, ~h v b v r v j v ~e v ~b, ~h v f v n v b v m v ~e v ~o v ~n v ~k v d, ~h v h v h v h v l v j, ~h v m, ~g v ~l v ~j v ~j v ~l v ~b v ~r v ~m v ~g v p, ~g v ~d v ~p v g v ~i v r v ~b, ~g v d v j v ~j v k, ~g v f v ~b v g v b v i v ~p, ~f v ~n v i v ~o v ~q v b v ~c v b, ~e v ~i v g v ~o v ~m v ~q v ~n v ~c, ~d v ~r v g v ~l v ~d v ~n, ~d v j v ~g v r v m v ~o v ~g v h v c v ~f, ~c v ~m v i v ~b v ~r v ~j v e v ~b v i, ~c v ~k v m, b v ~e v d v r v ~m v c v d v h, b v i v ~i v d, c v ~l, c v d v ~g, c v e v ~k v ~j v e v ~r v d v ~c v b v j, e v ~k v g v f, e v f v ~f v ~r v ~g v h v q v ~b, e v l, f v ~r v k v ~f v d v ~e v r v l, f v ~p v ~r v n, f v ~k v ~d v q v j v ~g, f v ~h v ~q, f v f v ~b v f v ~n, f v l v ~b v c v p v c v ~r v ~o, f v p v ~n v ~j v r v ~i v k v d v m v k, g v ~f v q, g v ~e v j v ~i v d v h, h v ~m v ~o v ~l v m v ~i, h v b v k v ~e, i v ~i v b v ~l v ~q v q v h, i v h v p v c v ~r v ~n, j v ~j v ~f v b v ~d, j v l v r, k v ~m v ~o v ~r, l v ~r v p v ~d v ~g v b v ~e, l v ~g v ~m v k v i, l v l v ~o v g, l v r v b v q v q, m v ~o, m v ~h v c v j, m v ~e v k v ~d v d, m v n v g v i v ~h v r v ~n, n v ~n v ~b v f, n v ~k v ~q v ~o v ~q v ~g v ~m v ~g, n v ~g v h v q v ~j v c v h, n v d v d v q v b v q v p, n v n v ~c v ~h v ~o, n v p v o v o v ~j v ~g v q v i v q, o v ~h v ~k v ~c, o v j v o v j v f, o v k v ~g, p v f v ~o v ~p v ~o v q v ~i v ~q v b v ~c, q v ~e v ~o v r v e v ~p, q v n v p v k v ~g, r v ~o v f v o v g, r v c, r v e, r v e v ~f v m v ~r v ~d v ~o v ~k v ~g, r v p v p v ~q v d v c v ~b v m], 500, count(435)).
tests(big_tests4, performance, [~r v ~k v ~h, ~r v ~g v l v o v l v ~c v ~h v ~j, ~r v g v g v ~j v g v ~n v ~j v ~b v ~e v ~o, ~r v m v i v c v ~n v ~b, ~q v ~r v p v ~n v ~b v ~q, ~q v ~q v ~m v r v e v e v ~c v ~i, ~q v f v ~i v f v r v g v p, ~p v ~e v ~d v ~h v ~q v l, ~p v j v ~f v n v ~q v q, ~p v p v ~q v p v ~f v e v e v ~r, ~o v ~p v ~j v ~l v b v ~h v i v ~i v ~o v k, ~o v ~l v b v n v p v ~r v b v ~m v ~l, ~o v ~j v b v l v ~g v ~m, ~o v ~g v ~e v f v i v ~m v ~e, ~o v ~f v g, ~o v ~b v f v f v h v ~i v ~n, ~n v ~o v ~f v c v ~n, ~m v ~q v ~l v ~e, ~m v ~o v ~o v ~i v ~k v ~m v ~h v ~f, ~m v ~m, ~l v ~c v c v ~f v ~c v ~b, ~l v c v ~h v p v r v i v ~k, ~l v d v ~h v i v ~i v ~e v ~n v g v n, ~k v ~g v ~i v ~n, ~k v n v d v ~b v d v g v ~q v ~i v d, ~j v ~f v c v ~j v h v g v f, ~j v f v c v e v b v p, ~j v k v l v o v ~c v p v ~e v ~h v k, ~j v m, ~j v m v ~q v h v ~f v ~o v ~m v o v k, ~j v m v m v ~l v m v ~q v ~r, ~j v o v ~m v f v n v d, ~i v ~r v b v m v ~c, ~i v ~p, ~i v ~b v j v n v ~f v ~e v h v ~m v ~g, ~i v b v ~m v ~d v ~l v f v ~o v h v ~c, ~i v c v g v ~d v o, ~i v f v k v f v m v b v ~h v ~q v ~n, ~h v ~h v ~j v ~f v ~l, ~h v ~h v d v b v i v m v q v ~d, ~h v ~f v c v f v d v e, ~h v d v e v ~f v ~o v g v ~p v ~m v e, ~h v f v b v r v ~q v f v j v n v l, ~h v i, ~g v ~f v ~l v d v ~j v d, ~g v h v ~e v q v ~c, ~g v r v p v j v j v c v k v ~k v ~g v ~b, ~f v ~l v ~i v h, ~f v ~h v i v ~n v ~m v ~d v ~q v r, ~e v ~g v j v o, ~e v p v f, ~d v ~i v ~q v j, ~d v l v ~b v n v ~p v ~i v ~e, ~b v j v b, ~b v j v n v o v p v ~l v f v ~b v p, ~b v n v ~f v ~p v p v k, b v ~r, b v e v ~g v m v p v ~c v ~d v ~b v ~q, b v g v c v ~d v ~k v o, c v k v ~f v i v ~q v ~f, d v e v k v i v n v ~k v ~r, d v o v ~k v m v ~b v ~h v o v q, e v ~h v ~j v ~q v ~f v ~d v ~c v ~e v b, f v ~m v j, f v ~h v ~g v ~m v ~m v q v ~j, f v ~d v m v ~o v h v ~m v q v d v ~j v q, f v d v ~o v i, f v h v ~d v f v ~j v ~m v b v ~k v ~d, f v n v ~p v ~h v j v ~g v ~d v ~p, f v p v ~k v f v ~g v ~r v ~r v ~d v ~h v h, g v ~n v ~p v ~i v c v ~j v r v k v d v f, g v ~j v k v ~n v j v o v ~b v ~p, h v ~i, h v n v ~q v ~d v i, h v p v l v l, i v ~h v ~i v ~e v ~i v ~h v d v ~k, i v j v ~m v h v q v q v l v ~o, i v q v m v p v ~g v p, j v i v ~e, j v n v ~l v h v ~o v ~o v d, k v ~n v ~l v c v ~g v g v f v g v ~p, k v ~k v b v f v ~i v ~m v ~l, l v ~g v b v ~o v r v ~f v ~c v q v ~k, l v q v ~l, m v ~q v m v e v ~j v ~o v ~o, m v ~h v i v ~b v g v r, m v q v ~e, n v ~l v ~m v b v ~f v f v ~o v ~m v d v ~m, n v ~c v o v d v ~f, n v c v i v k v ~n v ~p v ~g, o v ~k v g v ~p v o v ~m v c v ~b, o v ~j v ~d v d v ~e, o v b v i, p v n v r v f v ~g, q v ~i v ~j v ~j v ~c, q v ~e v ~d v n v l v i v ~p, q v c, r v c v q v j v j v ~p v ~g v ~l v ~n, r v j v ~n v r v k v p v ~q, r v p v i v ~o v ~l v d], 500, count(736)).
tests(big_tests5, performance, [~r v ~o v f v h v ~h v j v q v ~h, ~r v ~c v g v h v ~b v ~p, ~q v ~j v ~q v ~f v o v ~j, ~p v c v ~l v b v j v f v m, ~p v n v ~h v c v ~d v ~l v p v ~h, ~n v ~h v ~o v k v ~e v ~o v ~q v o, ~n v ~f v ~o v ~k v ~i v b, ~n v g v ~j v ~d v ~i v ~r v ~g, ~n v k, ~n v p, ~n v q v r v k v ~n, ~m v ~m v ~q v ~o, ~m v ~c v l v p v c v ~r v k v h v q v ~k, ~m v h, ~m v l v ~l v ~r v ~h v h v ~r v d v ~c, ~m v l v l, ~m v n, ~l v ~q v ~o v h v h v j v ~f v k v j, ~l v ~l v c v g v ~n v i v g v q, ~l v ~e v ~j v ~f v ~k v ~d v ~n v h v ~k v ~h, ~k v ~g v ~b, ~k v g v f v i v b v b v ~k v ~j, ~k v j v ~l, ~k v q v e v ~k v ~f v ~l, ~j v b v ~r v b v e v ~j v k v p, ~j v j v ~d v o v f v ~m v j v f v n v ~h, ~j v m v ~k v h v ~m, ~i v ~g v ~c v ~n v ~c v ~k v f v ~e, ~i v e v d v ~c v r, ~i v f v ~q v p, ~i v o, ~i v p, ~h v ~j, ~g v ~o v g v d v r v ~f, ~g v ~o v h v ~o v ~j v ~i v ~f v ~j v m, ~g v ~e v ~h v ~e v p, ~g v h v ~j v ~i v e v e v e, ~f v c v e, ~f v i v ~o v o v d, ~f v j v ~i v ~c, ~f v k v o v r v ~c v f v h, ~f v n v ~k, ~e v ~o v k v ~o v ~e v h, ~e v ~f v f, ~d v ~j v b v ~n v g v ~b v j v ~f v ~p, ~d v l v ~q v ~m, ~c v ~o v q v g v i v ~o v ~i v ~o v ~g, ~c v ~m v e, ~c v ~c, ~c v d v ~h v ~i v ~e, ~b v ~e v d v m v ~o, ~b v d v h v ~h v l v ~d, b v ~o v ~g v d v l v j v l v ~i v r v h, b v ~o v r v ~l, b v q, c v k v o v ~i v ~r v e, d v ~c v g v o v e v ~q v ~o v r v c v o, d v p v i v b v ~p, e v ~k v g, e v ~b, e v ~b v ~d, e v f v ~c v ~h v ~j v ~p v ~r v ~b, e v h v l v ~k v i v ~b, f v l v i v ~f v ~f v ~c v l v p v ~i v n, f v r v ~g v ~c v d v c v m v ~q v ~q, g v ~n v f v ~d v ~k v i v j v ~j v ~d, g v ~g v d v ~m v m v ~o v ~r v g v ~c, g v ~e v ~p v n v ~h v ~n, g v ~b v p, g v i v ~k v ~i, g v p v k v f v l v ~j v ~n v ~o, h v d v ~m, h v q v ~h v ~g v ~k v d v ~c v ~o v q, i v ~c v ~p v ~p v k v c v o v ~l v p, i v b v d v ~f v ~m v o v ~f, i v j v ~m v g, j v ~c v ~d v ~d v d, k v e v ~n v q, l v ~n v ~e v k v ~h, l v ~d v ~k, l v j v ~r v ~n v c v ~q v h v ~f v p v h, m v ~k v m v ~r, n v ~g v j v j v ~n v ~o v r v ~r v e v g, n v ~b v ~r v q, n v f v ~c v r v k, n v f v i v ~b v ~n v ~n v l v r, n v g v ~i v ~e v l, o v c v ~e v l v r v f v d v ~r v ~k v k, o v c v ~d v p v f v ~k v m, o v k, o v p v f v ~c v m v ~q v m, p v c, p v j v e v ~q v p v ~d v n v d v c, p v o v o v ~p v m v e v h v ~g, q v ~c v ~p v l v ~b v p v ~o v ~k v ~e, q v m, r v ~k v l v l v l, r v ~g v ~b v o v i, r v j v l v ~n v e v ~p v f v h v ~o v j, r v o v ~f v e v d], 500, count(127)).
tests(big_tests6, performance, [~r v p v ~o v ~c v n v j v ~q v r v ~e, ~r v r, ~q v k v ~f v c v ~b v ~h v ~f v ~n v n v ~g, ~q v o v ~r, ~p v ~j v m v c v n v m v p v ~o, ~o v ~g v g, ~o v c v ~i v ~l v e v ~o, ~o v r v p, ~n v l v ~d v ~q v ~m v ~g, ~m v ~e v ~r v q v ~r, ~m v d, ~m v i v ~j v p v ~k v ~l v i, ~l v ~l, ~l v ~h, ~l v ~g v n v m v ~q v ~f v f v r, ~l v ~b v ~b, ~l v c v ~k v q v p v q v ~h v ~h v ~p, ~l v c v p v n v ~q, ~k v ~n v ~e v ~k v c v o, ~k v c v ~r, ~k v i v ~h, ~j v ~m, ~j v ~c v ~f, ~j v f v ~q v ~n v p, ~i v ~i v i v d, ~i v g v ~k v ~m v i v m v r v ~d v ~b, ~h v ~r v q v ~d v b v ~r v ~b v n v h, ~h v c v ~e v ~e v ~k v ~m, ~h v l v ~o v p v ~h, ~g v ~o v ~l v d v ~k v ~q v ~e v c, ~g v ~o v ~i, ~g v ~m v ~k v ~e v ~f v o v ~r, ~g v ~e v ~o v ~n v o v k v ~m, ~g v b v r v ~o v c v e, ~g v n v i v ~f v ~e v k, ~f v p, ~e v ~o v ~b v ~j v e v ~h, ~e v ~g v ~r v p v c v ~f, ~e v j v e v ~m v e v ~d v j v ~o, ~d v ~q, ~d v ~o v ~r v h v f v k v f, ~d v ~d v k v l v k, ~d v g v q v o v ~h, ~c v h v ~o, ~b v ~b v ~p v ~q v ~j v o v p, ~b v b v q v ~e v ~j, ~b v n v j, b v ~j v ~q v ~j v r v ~b v e v ~i v d v ~m, b v ~h v ~j v l v ~k, b v ~c v p, b v r v m v ~o v j v o, c v ~g v b v ~j v ~j v ~c v ~p v o, c v c v ~f v ~o v ~g v ~l v ~c v d, c v k v q v c v ~b v o v ~p v g v ~k, c v m v ~o v j v g v k v p v ~e, c v m v ~j, d v ~j v ~l, e v ~r v c v f v o v ~c v m, e v ~n v ~c v o v ~r v j, e v ~e v ~o v ~f v ~b, f v ~m v ~g v ~e v ~h v o v ~o, f v b, f v m v ~m v ~g v ~f v ~q v e v b v ~o v n, g v ~r v q v b v p v k v ~b v ~h v e v p, g v c v o v ~d v n v ~l v ~l, g v p v r v ~j v ~i v o v l v ~k v g v ~l, h v j v o v ~k v ~p v ~h v j v k v r v m, i v ~l, i v f, j v ~p v ~h v ~b v ~b v f v l, j v e v ~m v ~j v ~p v ~b, k v ~i v ~g v ~j v n v n v i v ~b, k v ~g v ~p v b v c, k v b, k v o v ~r v ~k v g v g v o, l v ~r v ~n v ~m, l v ~o v ~q v ~q v q v ~d v b v c v f, l v ~c v ~h, m v ~r v ~e v ~e v h v ~q v ~d, m v ~o v ~b v q v m v i v ~k v c, m v p v k v ~i v ~f v ~d, n v ~r v ~q v ~g, n v ~f v ~d v ~o v j v ~f v r v ~m v ~n, n v h v f v ~n v o v d, o v ~l v ~p, o v ~i v ~e v f v ~n v n v p v ~f v ~d v p, p v ~p v ~e v ~d v ~k v j v ~l v ~b, p v ~m v ~n v m v p v ~m v i v ~p, p v ~d v d v ~e, p v k v l v p v ~i v h v ~k v b v ~g v ~g, q v ~m v ~h, q v ~i v ~l v ~g v ~q v ~p v ~g v ~p, q v ~f v ~j v ~i v i v d v b v d v ~j, q v l, q v p v ~o v ~b v f, r v ~h v ~i v i v p v ~g v p v ~d v m v n, r v d v ~m v i v g v ~n v ~c v r v ~l v ~g, r v j v ~o v ~p v ~i, r v r v e v g v ~l v r v j], 500, count(163)).
tests(big_tests7, performance, [~r v ~m v ~p v ~k v r v ~o v l v ~d v ~c v ~o, ~r v o v j v c v ~g v n v q v ~n v ~k, ~q v ~h v k v ~k v ~e v r v ~d v ~j, ~q v k v o v i v ~k v c v ~l v g, ~p v ~n, ~p v ~l v ~n v c, ~p v ~l v ~k v l v ~q v ~d v n v l v ~e v ~q, ~p v ~k, ~o v ~r v n v m v ~h v f v ~h, ~o v ~m v ~f v ~q v q v ~g v ~g v ~n v j v ~b, ~o v ~l v ~o v h v ~j, ~o v ~g v ~g v ~l v i v c v ~d v ~j, ~o v ~f v c v c v j, ~o v k v ~b v ~l v l v e v ~h v o v q, ~o v n, ~n v ~f v d v ~h v ~m v r v h, ~n v p v ~c v ~m v m v ~n, ~m v ~n v ~e, ~m v ~l v ~p v i, ~m v ~c v k v j, ~m v c, ~l v ~r v ~e v ~e v l v ~l v d v g, ~l v ~f v h v ~n v i, ~l v ~d v ~n v l v ~q v p v ~f v ~e v n, ~k v f v d v ~o v ~c v d v ~c v k v ~m, ~k v g, ~k v h v h v d v ~i, ~k v p v p v ~g v ~h v q v m v ~p, ~k v q v ~b v m, ~i v ~g, ~i v o v g v ~m v ~c v ~q v ~l, ~h v ~h v ~l v i v ~o, ~h v ~f v k v ~o v k v i v c v e, ~h v ~d v ~n v ~r, ~h v ~b v ~d v p v ~r v m v ~i v h v p, ~h v e v ~r v c v f v r v b, ~h v f v ~g v p v g v ~e v ~f, ~h v j, ~h v n v b v p v ~b v ~f v r v h v r v g, ~g v o v ~l v ~o v ~f v ~p v m v ~j, ~f v ~m v b v b v ~k v ~k v ~q, ~f v ~h v ~f v ~q v f v ~o, ~f v e v ~n v ~k v ~p v ~f v o v r, ~f v j v n v ~i v p v e v ~f v ~d v ~h v k, ~e v ~m v ~q v ~o v ~e v ~o v ~c, ~d v ~n v ~l v b v ~m v ~c v ~j v ~c v g, ~d v ~l v ~d, ~d v g v ~o v m v j v ~c v c v ~h v p v j, ~d v i v c v ~c v n v j v ~b v ~d v h, ~b v ~e, ~b v ~b, b v e v ~o v ~i v h v ~l v ~d v l v k v ~n, b v g v r v ~b v ~b v j v g v j, c v ~p v k v o v ~o v k v j, c v ~m v ~j v n, c v ~l v p v l v ~r v ~k, c v ~e v c v j v e v q, c v h v n v r, d v ~p v o v f v k v n v g v ~e, d v ~j v ~m, d v ~j v ~f, d v ~f, d v ~b v ~o v ~p v h v k v ~m, d v c v r v ~r v k v r, e v ~m v ~j v g v b, e v ~f v k v ~d v b v h v b v ~q v e, f v ~k v e v ~r v ~q v i v ~m, g v g v q, g v o, h v ~n, h v ~j v q, j v k v b v ~h v ~p v r v q v g v p v ~j, k v ~j v ~k v ~i, k v ~h v ~i v l v ~k v ~m v ~r, k v ~h v ~f v k v ~m v ~r, k v g v ~l v r v ~h v ~k v m v ~h v m, l v ~m v ~h v m v ~d v e v h v i v h, l v ~i v ~h v f, l v d v g v j v ~d v ~d v ~n v ~n, l v r v ~q v j v l v r v ~r, l v r v ~i v o v f v l v m v k v g v ~q, m v ~q v ~h v ~q v m v ~m v c v ~r v ~p v ~h, m v ~g v ~k v l v ~d v ~m v d v ~m v ~c v ~b, m v ~d v d v ~o v k v f, m v i, n v ~o v ~o, n v j v ~r v f v ~e v ~n v n v d v g, n v l v h v ~k v ~c, n v m v c v c v d v ~o v ~o v r v c, o v ~r v n v c v k v ~j v b, o v ~m v ~n, o v r, p v ~r v d v ~b v ~e v q v ~c v ~c, p v m v o, q v ~k v e v p v ~i v o v ~j v n v ~k v ~n, q v ~g v m v k v q v l v n v b v ~h v m, q v f v q v ~i v i v ~b v c v f v ~j v ~q, q v o v i v ~i v l v ~f v n v ~q v ~b, r v ~q v c v p v ~c, r v ~l v ~h v ~h], 500, count(37)).
tests(big_tests8, performance, [~r v h v k v ~q v ~o v ~g v ~g v ~h v p, ~r v p v ~p v ~d, ~q v ~m, ~q v ~l v ~n, ~o v ~r v n v ~j v k v l v ~i v ~f, ~o v ~k v ~l v ~l v l v i v ~q, ~o v ~i v i v b v ~i v ~o, ~o v b v j v ~e v ~h, ~o v f v r v g v ~m v i v ~p v p, ~o v g v ~k v ~g, ~n v ~h v l v ~e v ~k v ~b, ~n v e v e, ~n v k v ~e v h v l v ~q v ~f v j v h v i, ~m v n v ~c v ~l v c v ~q v c v l v ~l, ~l v ~l, ~l v ~i v ~c v q, ~l v q, ~k v ~l v ~j v l v k v d v p v ~q v ~o v g, ~k v c v ~f, ~j v ~i v q v ~o, ~j v j v ~b v ~j v k v ~r v p v k v f v d, ~j v k v ~p v ~q v f v b v ~r v h, ~j v p v f v q v ~k, ~j v q v p v k v ~e, ~i v ~p v o v ~i v q v b v ~o v n v f v n, ~i v ~k v ~r v ~r v ~h, ~i v o v o v ~p, ~h v ~l v n v r v ~j, ~h v ~d v b v k v d v j v c, ~h v ~c, ~h v l v ~p v ~i v o v ~g, ~h v n v ~o v ~n v n v d, ~g v ~m v ~o v ~b v b v r v ~e v r v ~j, ~g v ~g v ~l v d v m v ~e v ~f v ~p v ~q v ~h, ~g v ~g v ~c v p v l v ~q v ~h v m v ~p v p, ~g v ~d v ~m v ~l v j v ~h, ~g v i v ~e v ~q v b, ~f v ~m, ~f v ~k v h v ~n v r v ~e, ~f v ~e v i v k v ~k v i v i v c v ~e, ~f v b v ~k v g, ~e v ~n, ~e v ~l v ~i v c v l v ~n v ~q v ~n v g, ~e v ~j, ~e v ~h v ~r v ~h, ~d v ~q v ~f v c v p v e v ~q, ~d v ~b v ~n v r v i v ~i v c v ~j v b, ~d v ~b v ~c v n v e v q v d v d v ~k, ~c v ~g v j v ~d v n v g v ~o v r, ~c v ~e v ~r v ~j v r v d, ~b v ~d v ~e v o v ~r, b v i v o v ~r v o v e v i v ~r, c v h v f v n v e, c v l v c v r v b v q, c v n, d v ~o v f, d v ~l v ~l v f v r v k v ~q v r v c v p, e v ~i v ~b v ~i v r v ~l v ~m v ~o, e v k v p v ~l v ~l v ~d, f v ~p, g v ~r v r v ~g, g v ~q v f v ~n v i v ~g v o v ~e, g v d v h v o v e v ~o v ~l v b v ~d v k, g v k v f v p v r v ~p v ~m v ~b, h v ~n, h v ~i, h v o v ~l v ~l v ~q v ~h v o, i v ~f v ~m, i v ~e v ~j v ~c v e v r v g v ~i v d v ~h, i v e v ~d v e v n v ~j v ~l v n v ~h, i v q v p v g v ~n v e v m v b v ~k v j, j v ~j, j v ~h v d v ~p v ~c v ~o, j v b v ~b v ~d v ~f v c v o, j v h v p, j v r v b v n v n v ~h v ~d, k v ~d v ~d v ~g v e v e v j, k v o v m v ~p v ~f v ~c v ~r v ~i v i, l v ~r, l v e v b v ~n v d v c v e v ~d v c, l v k v e v ~k v o v b v ~r v ~f v ~b v n, m v ~k v o v ~r, m v e v c, m v p v ~l v n v m, n v l, n v o v ~h v ~c v ~r v e v ~n v ~b v ~l v ~l, o v ~m v ~k v d v ~i v c v ~k v d, o v ~l v ~q v h v ~d v ~o v ~m v ~k, o v ~d v ~p v ~e v b v e v p, o v ~d v ~g v m v h v ~g v ~o v ~d v q, p v ~j v j v q v b v ~n v ~g v ~c, p v f, q v ~p v ~n v q v q v n v ~p v ~h v q, q v ~i v ~g v ~j v j v ~i v p, q v ~d v ~k v b v g v k v ~b, r v ~r v f v ~i v ~l v l v k v ~n v i, r v ~j v ~c v b v ~g v p v i v ~o, r v ~e v ~r v ~l v n v m v c v ~q, r v h v c v ~l], 500, count(0)).
tests(big_tests9, performance, [~r v ~r v ~q v ~l v o v l v ~c v ~i v r, ~r v ~b v ~i v q, ~r v m v ~l v c, ~q v ~r v m, ~q v ~n v ~r v p v ~m v e v ~p v ~g, ~q v r v ~m v f v f v i v q v ~d v ~l, ~p v ~f v ~k v e v j v c v j v e, ~p v ~b, ~p v e v f v g, ~o v ~l, ~o v d v ~g v r, ~n v ~n v ~o, ~n v d v e v ~p v g v ~f, ~n v g v ~l v ~g v ~q v ~h v ~n v k v ~q, ~m v ~j, ~l v ~n, ~l v ~d v ~k, ~l v l v ~l, ~j v ~k v b v p, ~j v ~f v ~n v ~q v ~j, ~j v m v h v ~h v ~h v ~p v ~j, ~h v ~g v ~l v ~r, ~h v ~g v ~i, ~g v ~p v ~g v ~q v c v ~j v l v n, ~f v ~q v ~b v m, ~f v ~o v d v ~j v i v k v ~m v i v e v ~q, ~f v k v o v n v h v k v ~n v h v ~l, ~f v m v d v r v ~k v o v o v e, ~f v m v q v m v ~b v f v ~q v r, ~f v n v n v q v n, ~e v ~q v k v ~q v ~o v j v ~q v i, ~e v ~c v b v g v q v i v ~g v ~r, ~e v c v r v ~c, ~e v e v ~o v q v ~h v ~b v i v o v b v n, ~e v f v ~n, ~e v r v m v ~d, ~d v ~b v g v o v ~o v c v b v k, ~d v ~b v o v b v r v ~o v b, ~c v ~i, ~c v p v ~p v d v ~c v ~m, ~b v ~l v ~b v l v i, ~b v ~h, ~b v b v ~j v ~g v ~n v r v ~h, ~b v c v m v ~g v ~i, ~b v q v ~q, b v ~n v ~j v ~d v ~o v ~c v o, b v e v ~f v ~m v ~i, b v m v ~g v h v h v ~i v n v q, c v ~p v ~n v ~r v ~r v ~o v ~b v ~h v k v f, c v ~d v ~k v ~l v q v o, c v l v d v ~k, c v r, d v ~r v ~f v ~j v ~p, d v ~l v ~c v ~k, d v q v o v ~j v ~i, e v ~p v ~c v ~d v e v ~h v k, e v ~p v h v ~g v ~q v ~m v r v c, e v ~g v ~h v k v ~o v ~e, e v b v ~b v ~r v f v m v ~p v n v ~f, e v f v g v ~i v ~f, f v ~k v l v ~e v ~i v l v q v j v f v r, f v ~h v g v ~c v h v ~h v g v ~i v ~i, f v e, g v ~r v ~e v l v ~n v f, g v b v q v ~n v k v c v j v ~d v p, g v d, h v ~d v ~h, h v e v c v ~e v g, i v ~o v ~m, i v ~o v g v ~g v ~h v j v ~n v ~p v p v ~o, i v ~m v b v ~n v ~i v ~h v n v ~i v h v r, j v ~g v ~m v f v d v ~d v h, k v ~p v ~f v ~q v j v ~b v j v h v q, k v ~g v ~k v ~i v q, k v b v c v d v ~i v g v ~n v ~e v ~d, k v o v d v c v l v ~m v k v ~o v ~m v ~o, l v h v h v h v ~g v q v i v n, l v i v c v k v f v l v n v k v ~n v m, m v c v ~f, n v ~k v ~d v i v e v o v o, n v ~f v m v ~e v ~o, n v c v ~o v ~r v m v ~b, n v d, n v k v h v ~h v g v d v p v k v ~d, o v ~i v ~p v ~i v l v j v ~i v ~g v c v p, o v g v ~g v e, o v h v g v ~g v ~h v j v ~r, o v k, p v ~q v n v ~i v ~f v ~q v p, p v k v ~k v r v o v m v ~m v ~g v ~p v r, q v ~e v g v n v h v ~f v b v b v j, q v l v e v h v f, q v n v n v ~k v f v h v j v c v ~g, q v o v g v n v o, r v ~o v ~o, r v ~k v c v f v f v n v ~n v c v ~f v ~e, r v ~g v n v n v r, r v ~f v ~j v ~e v g, r v b v ~l v l v ~q v ~c v ~j, r v o v r v ~o v n], 500, count(411)).